
# small update.. 

print("---")

##from os import strerror
##
##try: 
##    for x in open("C:/Users/agrey/Desktop/Python/notes/tzop.txt", "rt"):
##        print(x)
##except IOError as e:
##    print("I/O error occurred: ", strerror(e.errno))

import random

##for i in range(10):
##    print(random.randrange(0, 10, 3))

for i in range(20):
    print(random.randrange(10, 100, 3))

##for i in range(10):
##    print(random.choice((0, 10, 3)))

print("end.")

#C:\Users\agrey\Desktop\Python\notes

